variables:
  DOCKERFILE: "Dockerfile_React"
  IMAGE_NAME: "myapp"
  PORT: "5173"

stages:
  - test_react
  - build_react_image
  - test_react_image
  - deploy_react

test_job:
  stage: test_react
  script:
    - echo "Running unit test"

build_image_job:
  stage: build_react_image
  script:
    - echo "Building docker image"
    - docker build -t ${IMAGE_NAME}:$CI_COMMIT_REF_NAME -t ${IMAGE_NAME}:latest -f ${DOCKERFILE}

test_image_job:
  stage: test_react_image
  script:
    - echo "Running docker image to test"
    - docker run -p ${PORT}:${PORT} ${IMAGE_NAME}:$CI_COMMIT_REF_NAME --name ${IMAGE_NAME}_CICD

deploy_job:
  stage: deploy_react
  script:
    - echo "Deploying application"
