stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building docker image"

test_job:
  stage: test
  script:
    - echo "Running docker image to test"

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application"
